package com.example.core.crypto.ratchet

import com.example.core.crypto.EccCryptoEngine
import com.example.core.crypto.Hkdf
import java.security.KeyPair
import java.security.PublicKey
import java.util.concurrent.ConcurrentHashMap

/**
 * High-level Cryptographic Mesh Manager.
 * Orchestrates:
 * 1. Initial 3-DH / X3DH Handshake session bootstrap between peers.
 * 2. Active Double Ratchet sessions indexed by remote Peer Node ID.
 * 3. Forward Secrecy & Out-of-Order Message Decryption.
 * 4. Verification of Sender Identity Signatures.
 */
class MeshCryptoManager(
    private val ourIdentityKeyPair: KeyPair
) {
    // Active ratchet sessions mapped by peerNodeId
    private val sessions = ConcurrentHashMap<String, DoubleRatchetSession>()

    /**
     * Public Identity Key (compressed 33-byte format).
     */
    val identityPublicKeyCompressed: ByteArray
        get() = EccCryptoEngine.encodePublicKeyCompressed(ourIdentityKeyPair.public)

    /**
     * Human-scannable Fingerprint (e.g., "ABCD:1234:5678:90EF").
     */
    val identityFingerprint: String
        get() = EccCryptoEngine.computeNodeFingerprint(ourIdentityKeyPair.public)

    /**
     * Signs data with our long-term hardware Identity Key.
     */
    fun sign(data: ByteArray): ByteArray {
        return EccCryptoEngine.sign(ourIdentityKeyPair.private, data)
    }

    /**
     * Verifies sender signature using their identity public key.
     */
    fun verifySignature(peerIdentityPublicKey: PublicKey, data: ByteArray, signature: ByteArray): Boolean {
        return EccCryptoEngine.verify(peerIdentityPublicKey, data, signature)
    }

    /**
     * Initiates a new cryptographic ratchet session with a remote peer given their Identity Key
     * and one-time ephemeral prekey.
     * Computes X3DH-style shared master secret using Diffie-Hellman combinations.
     */
    fun startInitiatorSession(
        peerNodeId: String,
        peerIdentityPublicKey: PublicKey,
        peerPrekeyPublic: PublicKey
    ): DoubleRatchetSession {
        // Ephemeral key generated by initiator
        val ephemeralKeyPair = EccCryptoEngine.generateKeyPair()

        // DH1 = DH(ourIK, peerPrekey)
        val dh1 = EccCryptoEngine.performEcdh(ourIdentityKeyPair.private, peerPrekeyPublic)
        // DH2 = DH(ourEK, peerIK)
        val dh2 = EccCryptoEngine.performEcdh(ephemeralKeyPair.private, peerIdentityPublicKey)
        // DH3 = DH(ourEK, peerPrekey)
        val dh3 = EccCryptoEngine.performEcdh(ephemeralKeyPair.private, peerPrekeyPublic)

        // Combine DH secrets: IKM = DH1 + DH2 + DH3
        val combinedIkm = dh1 + dh2 + dh3
        val sharedMasterKey = Hkdf.deriveKey(
            salt = "Mesh3DhSalt".toByteArray(Charsets.UTF_8),
            ikm = combinedIkm,
            info = "MeshRatchetBootstrap".toByteArray(Charsets.UTF_8),
            length = 32
        )

        val session = DoubleRatchetSession.initializeInitiator(
            peerNodeId = peerNodeId,
            sharedMasterKey = sharedMasterKey,
            peerRemoteDhPublicKey = peerPrekeyPublic
        )
        sessions[peerNodeId] = session
        return session
    }

    /**
     * Accepts a ratchet session on the receiver side given initiator's identity key,
     * initiator's ephemeral public key, and our local prekey pair.
     */
    fun acceptReceiverSession(
        peerNodeId: String,
        peerIdentityPublicKey: PublicKey,
        peerEphemeralPublicKey: PublicKey,
        ourLocalPrekeyPair: KeyPair
    ): DoubleRatchetSession {
        // DH1 = DH(ourPrekey, peerIK)
        val dh1 = EccCryptoEngine.performEcdh(ourLocalPrekeyPair.private, peerIdentityPublicKey)
        // DH2 = DH(ourIK, peerEK)
        val dh2 = EccCryptoEngine.performEcdh(ourIdentityKeyPair.private, peerEphemeralPublicKey)
        // DH3 = DH(ourPrekey, peerEK)
        val dh3 = EccCryptoEngine.performEcdh(ourLocalPrekeyPair.private, peerEphemeralPublicKey)

        val combinedIkm = dh1 + dh2 + dh3
        val sharedMasterKey = Hkdf.deriveKey(
            salt = "Mesh3DhSalt".toByteArray(Charsets.UTF_8),
            ikm = combinedIkm,
            info = "MeshRatchetBootstrap".toByteArray(Charsets.UTF_8),
            length = 32
        )

        val session = DoubleRatchetSession.initializeReceiver(
            peerNodeId = peerNodeId,
            sharedMasterKey = sharedMasterKey,
            ourPreSharedKeyPair = ourLocalPrekeyPair
        )
        sessions[peerNodeId] = session
        return session
    }

    /**
     * Encrypts plaintext message for peerNodeId using their active Double Ratchet session.
     */
    fun encryptForPeer(peerNodeId: String, plaintext: ByteArray): RatchetMessage {
        val session = sessions[peerNodeId]
            ?: throw IllegalStateException("No active ratchet session established with peer: $peerNodeId")
        return session.encrypt(plaintext)
    }

    /**
     * Decrypts ciphertext message from peerNodeId using their active Double Ratchet session.
     */
    fun decryptFromPeer(peerNodeId: String, message: RatchetMessage): ByteArray {
        val session = sessions[peerNodeId]
            ?: throw IllegalStateException("No active ratchet session established with peer: $peerNodeId")
        return session.decrypt(message)
    }

    fun getSession(peerNodeId: String): DoubleRatchetSession? = sessions[peerNodeId]

    fun getAllSessions(): List<RatchetSessionState> {
        return sessions.values.map { it.getSessionSnapshot() }
    }
}
